version: '3.7'
services:
  site:
    container_name: docsy
    command: jekyll serve --no-watch --drafts --incremental
    #command: jekyll build    
    image: jekyll/jekyll:3.8
    volumes: 
      - "./:/srv/jekyll"
      - "./vendor/bundle:/usr/local/bundle"
      # remove "./vendor/bundle:/usr/local/bundle" volume when deploying in production
    ports: 
      - "4000:4000"
