# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Grant permissions
      run: sudo chown -R $(whoami):$(whoami) ./ 

    - name: Create target folder
      run: sudo mkdir ./_site

    - name: Build site with docker-compose
      run: docker-compose up
    
    - name: Take a look at site content
      run: ls ./_site
      
    - name: find running container
      run: docker ps -a
      
    - name: sync-files-ftp
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: baconao.net
        username: baconao_posts@baconao.net
        password: +(b5y.,T_0EC
        local-dir: ./_site/
        server-dir: ./
        state-name: ./sync.json

    # Sync website from github
    #- name: ftp-action
    #  uses: sebastianpopp/ftp-action@v2.0.0
    #  with: 
    #    host: baconao.net
    #    user: baconao_posts@baconao.net
    #    password: +(b5y.,T_0EC
    #    localDir: ./_site
    #    forceSsl: true
    #   remoteDir: .
        
        
